const coreDemoUsers = [
  {
    key: 'buyer-primary',
    role: 'BUYER',
    name: 'Maya Chen',
    organization: 'Northstar Capital',
    email: 'maya@example.test',
    countryCode: 'GB',
    profileSummary: 'Acquires regulated payments and fintech businesses across Europe.',
  },
  {
    key: 'buyer-second',
    role: 'BUYER',
    name: 'Owen Brooks',
    organization: 'Harbour Growth',
    email: 'owen@example.test',
    countryCode: 'IE',
    profileSummary: 'Looks for profitable financial software and licence-led acquisitions.',
  },
  {
    key: 'buyer-third',
    role: 'BUYER',
    name: 'Elena Rossi',
    organization: 'Aurelia Partners',
    email: 'elena@example.test',
    countryCode: 'IT',
    profileSummary: 'Targets payment and EMI assets with small operating teams.',
  },
  {
    key: 'seller-primary',
    role: 'SELLER',
    name: 'Daniel Ward',
    organization: 'Atlas Deal Advisory',
    email: 'daniel@example.test',
    countryCode: 'GB',
    profileSummary: 'Represents regulated financial assets and operating companies.',
  },
  {
    key: 'seller-second',
    role: 'SELLER',
    name: 'Sofia Marin',
    organization: 'Meridian Assets',
    email: 'sofia@example.test',
    countryCode: 'LT',
    profileSummary: 'Lists fintech and EMI opportunities in the EEA.',
  },
  {
    key: 'manager',
    role: 'PLATFORM_MANAGER',
    name: 'Alex Morgan',
    organization: 'Deals Demo',
    email: 'manager@example.test',
    countryCode: 'GB',
    profileSummary: 'Marketplace quality and compliance operations.',
  },
] as const;

const extraBuyerSpecs = [
  [
    'buyer-04',
    'Priya Nair',
    'Northbridge Ventures',
    'NL',
    'Targets B2B SaaS and fintech with recurring revenue.',
    400000,
    3500000,
    ['NL', 'DE', 'GB'],
    ['FINTECH'],
    ['ACTIVE', 'PROFITABLE'],
    8,
    80,
  ],
  [
    'buyer-05',
    'Lukas Weber',
    'Rheinland Capital',
    'DE',
    'Invests in profitable compliance and payments platforms in DACH.',
    1000000,
    8000000,
    ['DE', 'AT', 'CH'],
    ['FINTECH', 'PAYMENT'],
    ['PROFITABLE', 'ACTIVE'],
    10,
    120,
  ],
  [
    'buyer-06',
    'Sophie Laurent',
    'Meridian Search Fund',
    'FR',
    'Seeks owner-operated B2B software with clear cash generation.',
    750000,
    4000000,
    ['FR', 'BE', 'LU'],
    ['FINTECH'],
    ['PROFITABLE', 'ACTIVE'],
    4,
    50,
  ],
  [
    'buyer-07',
    'Marco Bianchi',
    'Cobalt Partners',
    'IT',
    'Looks for licensed financial services assets in Southern Europe.',
    500000,
    2500000,
    ['IT', 'ES', 'PT'],
    ['PAYMENT', 'EMI'],
    ['ACTIVE', 'LICENSE_ONLY'],
    2,
    35,
  ],
  [
    'buyer-08',
    'Anna Kowalska',
    'Vistula Growth',
    'PL',
    'Acquires scalable software companies serving regulated industries.',
    300000,
    1800000,
    ['PL', 'CZ', 'SK'],
    ['FINTECH'],
    ['ACTIVE', 'PROFITABLE'],
    3,
    45,
  ],
  [
    'buyer-09',
    'Tom Evans',
    'Harbour Search Partners',
    'GB',
    'Buys profitable vertical SaaS with recurring contracts and retention.',
    1200000,
    7000000,
    ['GB', 'IE'],
    ['FINTECH'],
    ['PROFITABLE'],
    10,
    100,
  ],
  [
    'buyer-10',
    'Niamh Kelly',
    'Emerald Strategic',
    'IE',
    'Seeks Irish and UK technology businesses for strategic add-on acquisitions.',
    500000,
    3000000,
    ['IE', 'GB'],
    ['FINTECH'],
    ['ACTIVE', 'PROFITABLE'],
    5,
    70,
  ],
  [
    'buyer-11',
    'Jonas Berg',
    'Nordic Bridge',
    'SE',
    'Invests in compliant digital infrastructure across the Nordics.',
    800000,
    5000000,
    ['SE', 'DK', 'NO', 'FI'],
    ['FINTECH', 'CRYPTO'],
    ['ACTIVE', 'PROFITABLE'],
    6,
    90,
  ],
  [
    'buyer-12',
    'Eva Novak',
    'Danube Holdings',
    'AT',
    'Targets compact regulated operators with room for operational improvement.',
    250000,
    2200000,
    ['AT', 'DE', 'CZ'],
    ['PAYMENT', 'EMI'],
    ['ACTIVE', 'LICENSE_ONLY'],
    1,
    30,
  ],
  [
    'buyer-13',
    'James Miller',
    'Pinecrest Equity',
    'US',
    'Looks for established fintech infrastructure and payments enablement.',
    2000000,
    12000000,
    ['GB', 'IE', 'NL'],
    ['PAYMENT', 'FINTECH'],
    ['ACTIVE', 'PROFITABLE'],
    15,
    200,
  ],
  [
    'buyer-14',
    'Carla Mendes',
    'Lusitania Capital',
    'PT',
    'Acquires profitable B2B businesses in Iberia with strong local teams.',
    600000,
    4500000,
    ['PT', 'ES'],
    ['FINTECH'],
    ['PROFITABLE', 'ACTIVE'],
    5,
    80,
  ],
  [
    'buyer-15',
    'David Cohen',
    'Atlas Family Office',
    'IL',
    'Seeks minority-friendly technology and financial services opportunities.',
    1000000,
    6000000,
    ['GB', 'DE', 'IL'],
    ['FINTECH', 'PAYMENT'],
    ['ACTIVE', 'PROFITABLE'],
    5,
    100,
  ],
  [
    'buyer-16',
    'Marta Silva',
    'Iberia Operators',
    'ES',
    'Operator-led buyer focused on profitable payments and compliance software.',
    350000,
    2500000,
    ['ES', 'PT', 'IT'],
    ['PAYMENT', 'FINTECH'],
    ['ACTIVE', 'PROFITABLE'],
    2,
    40,
  ],
  [
    'buyer-17',
    'Felix Hartmann',
    'Alpine Digital',
    'CH',
    'Targets premium B2B software with defensible recurring revenue.',
    1500000,
    9000000,
    ['CH', 'DE', 'AT'],
    ['FINTECH'],
    ['PROFITABLE'],
    12,
    120,
  ],
  [
    'buyer-18',
    'Grace Osei',
    'Cedar Impact Capital',
    'GB',
    'Invests in accessible financial infrastructure and responsible growth.',
    500000,
    3500000,
    ['GB', 'FR', 'NL'],
    ['PAYMENT', 'FINTECH'],
    ['ACTIVE', 'PROFITABLE'],
    4,
    75,
  ],
  [
    'buyer-19',
    'Henrik Larsen',
    'Baltic Growth Fund',
    'DK',
    'Seeks EEA licence-led opportunities and transition-ready teams.',
    400000,
    2800000,
    ['DK', 'LT', 'EE'],
    ['EMI', 'PAYMENT'],
    ['ACTIVE', 'LICENSE_ONLY'],
    1,
    30,
  ],
  [
    'buyer-20',
    'Claire Dubois',
    'Riviera Ventures',
    'FR',
    'Acquires profitable specialist software with international customers.',
    900000,
    5500000,
    ['FR', 'BE', 'CH'],
    ['FINTECH'],
    ['PROFITABLE', 'ACTIVE'],
    7,
    90,
  ],
] as const;

const extraSellerSpecs = [
  [
    'seller-03',
    'Michael Reed',
    'Crownstone M&A',
    'GB',
    'Advises owners of UK technology and regulated services businesses.',
  ],
  [
    'seller-04',
    'Laura Garcia',
    'Iberian Deal Partners',
    'ES',
    'Represents founder-led software and payments opportunities across Iberia.',
  ],
  [
    'seller-05',
    'Katrin Fischer',
    'Hanseatic Advisory',
    'DE',
    'Lists profitable DACH software and compliance assets.',
  ],
  [
    'seller-06',
    'Robert Zielinski',
    'Eastgate Corporate Finance',
    'PL',
    'Supports owners preparing technology businesses for a discreet sale.',
  ],
  [
    'seller-07',
    'Ingrid Svensson',
    'North Sea Transactions',
    'SE',
    'Markets Nordic fintech and infrastructure opportunities.',
  ],
  [
    'seller-08',
    'Matteo Conti',
    'Orion Asset Advisors',
    'IT',
    'Advises on licensed financial assets and strategic acquisitions.',
  ],
] as const;

const extraBuyers = extraBuyerSpecs.map(
  ([key, name, organization, countryCode, profileSummary]) => ({
    key,
    role: 'BUYER' as const,
    name,
    organization,
    email: `${key}@example.test`,
    countryCode,
    profileSummary,
  }),
);

const extraSellers = extraSellerSpecs.map(
  ([key, name, organization, countryCode, profileSummary]) => ({
    key,
    role: 'SELLER' as const,
    name,
    organization,
    email: `${key}@example.test`,
    countryCode,
    profileSummary,
  }),
);

export const demoUsers = [...coreDemoUsers, ...extraBuyers, ...extraSellers] as const;

const coreBuyerProfiles = [
  {
    userKey: 'buyer-primary',
    investmentThesis:
      'Acquire an operating payments or EMI business in the UK or EEA with a manageable team and an asking price below EUR 2 million.',
    budgetMinEur: 300000,
    budgetMaxEur: 2000000,
    targetCountries: ['GB', 'LT', 'MT'],
    targetCategories: ['PAYMENT', 'EMI'],
    targetLicenseTypes: ['EMI', 'PI', 'FCA'],
    targetBusinessStatuses: ['ACTIVE'],
    minEmployees: 2,
    maxEmployees: 25,
  },
  {
    userKey: 'buyer-second',
    investmentThesis:
      'Acquire profitable fintech software with recurring revenue in Ireland or the United Kingdom.',
    budgetMinEur: 500000,
    budgetMaxEur: 5000000,
    targetCountries: ['IE', 'GB'],
    targetCategories: ['FINTECH'],
    targetLicenseTypes: [],
    targetBusinessStatuses: ['PROFITABLE', 'ACTIVE'],
    minEmployees: 5,
    maxEmployees: 60,
  },
  {
    userKey: 'buyer-third',
    investmentThesis:
      'Seek licence-led payment opportunities in Southern Europe with a compact operating team.',
    budgetMinEur: 250000,
    budgetMaxEur: 1500000,
    targetCountries: ['IT', 'MT'],
    targetCategories: ['PAYMENT', 'EMI'],
    targetLicenseTypes: ['EMI'],
    targetBusinessStatuses: ['ACTIVE', 'LICENSE_ONLY'],
    minEmployees: 1,
    maxEmployees: 20,
  },
] as const;

const extraBuyerProfiles = extraBuyerSpecs.map(
  ([
    userKey,
    ,
    ,
    ,
    ,
    budgetMinEur,
    budgetMaxEur,
    targetCountries,
    targetCategories,
    targetBusinessStatuses,
    minEmployees,
    maxEmployees,
  ]) => ({
    userKey,
    investmentThesis: `Acquire a ${targetCategories.join(' or ').toLowerCase()} business in ${targetCountries.join(', ')} with a clear operating profile and sustainable economics.`,
    budgetMinEur,
    budgetMaxEur,
    targetCountries,
    targetCategories,
    targetLicenseTypes: targetCategories.some(
      (category) => category === 'PAYMENT' || category === 'EMI',
    )
      ? ['PI', 'EMI']
      : [],
    targetBusinessStatuses,
    minEmployees,
    maxEmployees,
  }),
);

export const buyerProfiles = [...coreBuyerProfiles, ...extraBuyerProfiles] as const;

const coreDemoAssets = [
  {
    sellerKey: 'seller-primary',
    title: 'UK Payment Institution',
    summary:
      'Fictional operating payment institution with multi-currency capabilities and a compact team.',
    description:
      'A fictional due-diligence-ready listing created only for the prototype. It demonstrates a regulated operating business, clear commercial facts, and Buyer matching.',
    category: 'PAYMENT',
    countryCode: 'GB',
    licenseType: 'FCA PI',
    regulator: 'Financial Conduct Authority',
    businessStatus: 'ACTIVE',
    askingPriceEur: 1250000,
    employeeCount: 12,
    highlights: [
      'Multi-currency payment rails',
      '12-person operating team',
      'Fictional clean compliance record',
    ],
  },
  {
    sellerKey: 'seller-second',
    title: 'Lithuanian EMI Licence',
    summary: 'Fictional EEA electronic-money institution opportunity with passporting potential.',
    description:
      'A fictional licence-led asset used to evaluate filters, detail views, Smart Match, and marketplace contact flows.',
    category: 'EMI',
    countryCode: 'LT',
    licenseType: 'EMI',
    regulator: 'Bank of Lithuania',
    businessStatus: 'LICENSE_ONLY',
    askingPriceEur: 780000,
    employeeCount: 3,
    highlights: ['EEA jurisdiction', 'Compact transition team', 'Fictional licence package'],
  },
  {
    sellerKey: 'seller-primary',
    title: 'Irish RegTech Platform',
    summary: 'Fictional profitable compliance software business serving financial institutions.',
    description:
      'A fictional operating software company that broadens the demo inventory and makes category and price filters meaningful.',
    category: 'FINTECH',
    countryCode: 'IE',
    licenseType: null,
    regulator: null,
    businessStatus: 'PROFITABLE',
    askingPriceEur: 3200000,
    employeeCount: 34,
    highlights: ['Recurring SaaS revenue', '34-person team', 'Fictional enterprise customers'],
  },
  {
    sellerKey: 'seller-second',
    title: 'Malta Crypto Service Provider',
    summary: 'Fictional pre-revenue virtual-financial-asset licence opportunity.',
    description:
      'A fictional listing used to demonstrate status/category filtering and lower-confidence matching.',
    category: 'CRYPTO',
    countryCode: 'MT',
    licenseType: 'VFA',
    regulator: 'MFSA',
    businessStatus: 'PRE_REVENUE',
    askingPriceEur: 450000,
    employeeCount: 1,
    highlights: ['Malta jurisdiction', 'Pre-revenue setup', 'Fictional regulatory package'],
  },
] as const;

const extraAssetSpecs = [
  [
    'seller-03',
    'Dutch Compliance SaaS',
    'Recurring-revenue compliance workflow platform for European financial institutions.',
    'FINTECH',
    'NL',
    null,
    null,
    'PROFITABLE',
    2100000,
    28,
    ['Recurring B2B contracts', 'EU customer base', '28-person team'],
  ],
  [
    'seller-04',
    'Spanish Payment Gateway',
    'Operating payment gateway serving travel and subscription merchants across Iberia.',
    'PAYMENT',
    'ES',
    'PI',
    'Banco de España',
    'ACTIVE',
    1650000,
    18,
    ['Merchant recurring revenue', 'PCI-compliant operations', '18-person team'],
  ],
  [
    'seller-05',
    'German AML Platform',
    'Profitable transaction-monitoring software with enterprise financial-services customers.',
    'FINTECH',
    'DE',
    null,
    null,
    'PROFITABLE',
    4100000,
    42,
    ['Enterprise contracts', 'Recurring SaaS revenue', '42-person team'],
  ],
  [
    'seller-06',
    'Polish SME Lending Platform',
    'Active lending technology platform with a compact product and servicing operation.',
    'FINTECH',
    'PL',
    'Lending licence',
    'KNF',
    'ACTIVE',
    950000,
    15,
    ['SME lending workflow', 'Compact operations', 'Fictional clean compliance record'],
  ],
  [
    'seller-07',
    'Swedish Open Banking API',
    'API infrastructure business connecting European banks and regulated fintechs.',
    'FINTECH',
    'SE',
    'PI',
    'Finansinspektionen',
    'PROFITABLE',
    2800000,
    31,
    ['Developer-led distribution', 'Recurring API revenue', '31-person team'],
  ],
  [
    'seller-08',
    'Italian EMI Transition',
    'Licence-led electronic-money institution opportunity with a small transition team.',
    'EMI',
    'IT',
    'EMI',
    'Banca d’Italia',
    'LICENSE_ONLY',
    620000,
    4,
    ['EEA licence', 'Transition-ready team', 'Fictional regulatory package'],
  ],
  [
    'seller-03',
    'Belgian RegTech Workflow',
    'B2B regulatory reporting platform used by specialist financial institutions.',
    'FINTECH',
    'BE',
    null,
    null,
    'PROFITABLE',
    1350000,
    16,
    ['Recurring subscriptions', 'Low churn profile', '16-person team'],
  ],
  [
    'seller-04',
    'Portuguese Merchant Services',
    'Active merchant acquiring operation focused on hospitality and online commerce.',
    'PAYMENT',
    'PT',
    'PI',
    'Banco de Portugal',
    'ACTIVE',
    1150000,
    11,
    ['Merchant portfolio', 'Hospitality vertical', '11-person team'],
  ],
  [
    'seller-05',
    'Austrian Treasury SaaS',
    'Cash-management software for mid-market finance teams with recurring contracts.',
    'FINTECH',
    'AT',
    null,
    null,
    'PROFITABLE',
    1850000,
    22,
    ['B2B recurring revenue', 'Finance workflow', '22-person team'],
  ],
  [
    'seller-06',
    'Czech KYC Provider',
    'Identity and onboarding technology serving banks and regulated marketplaces.',
    'FINTECH',
    'CZ',
    null,
    null,
    'ACTIVE',
    890000,
    14,
    ['KYC automation', 'Regulated customers', '14-person team'],
  ],
  [
    'seller-07',
    'Danish Payments Processor',
    'Niche payments processor with established Nordic merchant relationships.',
    'PAYMENT',
    'DK',
    'PI',
    'Finanstilsynet',
    'ACTIVE',
    2400000,
    26,
    ['Nordic merchants', 'Processing infrastructure', '26-person team'],
  ],
  [
    'seller-08',
    'French Insurance Software',
    'Profitable policy-administration software serving specialist brokers.',
    'FINTECH',
    'FR',
    null,
    null,
    'PROFITABLE',
    3600000,
    38,
    ['Recurring licence revenue', 'Broker distribution', '38-person team'],
  ],
  [
    'seller-03',
    'Irish Credit Analytics',
    'Data and decisioning platform for lenders and alternative finance providers.',
    'FINTECH',
    'IE',
    null,
    null,
    'PROFITABLE',
    2700000,
    24,
    ['Decisioning IP', 'Recurring contracts', '24-person team'],
  ],
  [
    'seller-04',
    'Greek Travel Payments',
    'Payment orchestration platform built for travel and marketplace merchants.',
    'PAYMENT',
    'GR',
    'PI',
    'Bank of Greece',
    'ACTIVE',
    730000,
    9,
    ['Travel vertical', 'API-first product', '9-person team'],
  ],
  [
    'seller-05',
    'Swiss Wealth Reporting',
    'Secure reporting and client-portal software for independent wealth managers.',
    'FINTECH',
    'CH',
    null,
    null,
    'PROFITABLE',
    4600000,
    46,
    ['Wealth-management customers', 'High retention', '46-person team'],
  ],
  [
    'seller-06',
    'Romanian Fraud Intelligence',
    'Fraud detection software with a growing customer base in Central Europe.',
    'FINTECH',
    'RO',
    null,
    null,
    'ACTIVE',
    1250000,
    19,
    ['Risk analytics', 'Regional customer base', '19-person team'],
  ],
] as const;

const extraAssets = extraAssetSpecs.map(
  ([
    sellerKey,
    title,
    summary,
    category,
    countryCode,
    licenseType,
    regulator,
    businessStatus,
    askingPriceEur,
    employeeCount,
    highlights,
  ]) => ({
    sellerKey,
    title,
    summary: `Fictional ${summary.toLowerCase()}`,
    description: `A fictional marketplace listing for the prototype. ${summary} It includes enough commercial and operating context for buyer screening and explainable matching.`,
    category,
    countryCode,
    licenseType,
    regulator,
    businessStatus,
    askingPriceEur,
    employeeCount,
    highlights,
  }),
);

export const demoAssets = [...coreDemoAssets, ...extraAssets] as const;
