export const demoUsers = [
  {
    key: 'buyer-primary',
    role: 'BUYER',
    name: 'Maya Chen',
    organization: 'Northstar Capital',
    email: 'maya@example.test',
    countryCode: 'GB',
    profileSummary: 'Acquires regulated payments and fintech businesses across Europe.',
  },
  {
    key: 'buyer-second',
    role: 'BUYER',
    name: 'Owen Brooks',
    organization: 'Harbour Growth',
    email: 'owen@example.test',
    countryCode: 'IE',
    profileSummary: 'Looks for profitable financial software and licence-led acquisitions.',
  },
  {
    key: 'buyer-third',
    role: 'BUYER',
    name: 'Elena Rossi',
    organization: 'Aurelia Partners',
    email: 'elena@example.test',
    countryCode: 'IT',
    profileSummary: 'Targets payment and EMI assets with small operating teams.',
  },
  {
    key: 'seller-primary',
    role: 'SELLER',
    name: 'Daniel Ward',
    organization: 'Atlas Deal Advisory',
    email: 'daniel@example.test',
    countryCode: 'GB',
    profileSummary: 'Represents regulated financial assets and operating companies.',
  },
  {
    key: 'seller-second',
    role: 'SELLER',
    name: 'Sofia Marin',
    organization: 'Meridian Assets',
    email: 'sofia@example.test',
    countryCode: 'LT',
    profileSummary: 'Lists fintech and EMI opportunities in the EEA.',
  },
  {
    key: 'manager',
    role: 'PLATFORM_MANAGER',
    name: 'Alex Morgan',
    organization: 'Deals Demo',
    email: 'manager@example.test',
    countryCode: 'GB',
    profileSummary: 'Marketplace quality and compliance operations.',
  },
] as const;

export const buyerProfiles = [
  {
    userKey: 'buyer-primary',
    investmentThesis:
      'Acquire an operating payments or EMI business in the UK or EEA with a manageable team and an asking price below EUR 2 million.',
    budgetMinEur: 300000,
    budgetMaxEur: 2000000,
    targetCountries: ['GB', 'LT', 'MT'],
    targetCategories: ['PAYMENT', 'EMI'],
    targetLicenseTypes: ['EMI', 'PI', 'FCA'],
    targetBusinessStatuses: ['ACTIVE'],
    minEmployees: 2,
    maxEmployees: 25,
  },
  {
    userKey: 'buyer-second',
    investmentThesis:
      'Acquire profitable fintech software with recurring revenue in Ireland or the United Kingdom.',
    budgetMinEur: 500000,
    budgetMaxEur: 5000000,
    targetCountries: ['IE', 'GB'],
    targetCategories: ['FINTECH'],
    targetLicenseTypes: [],
    targetBusinessStatuses: ['PROFITABLE', 'ACTIVE'],
    minEmployees: 5,
    maxEmployees: 60,
  },
  {
    userKey: 'buyer-third',
    investmentThesis:
      'Seek licence-led payment opportunities in Southern Europe with a compact operating team.',
    budgetMinEur: 250000,
    budgetMaxEur: 1500000,
    targetCountries: ['IT', 'MT'],
    targetCategories: ['PAYMENT', 'EMI'],
    targetLicenseTypes: ['EMI'],
    targetBusinessStatuses: ['ACTIVE', 'LICENSE_ONLY'],
    minEmployees: 1,
    maxEmployees: 20,
  },
] as const;

export const demoAssets = [
  {
    sellerKey: 'seller-primary',
    title: 'UK Payment Institution',
    summary:
      'Fictional operating payment institution with multi-currency capabilities and a compact team.',
    description:
      'A fictional due-diligence-ready listing created only for the prototype. It demonstrates a regulated operating business, clear commercial facts, and Buyer matching.',
    category: 'PAYMENT',
    countryCode: 'GB',
    licenseType: 'FCA PI',
    regulator: 'Financial Conduct Authority',
    businessStatus: 'ACTIVE',
    askingPriceEur: 1250000,
    employeeCount: 12,
    highlights: [
      'Multi-currency payment rails',
      '12-person operating team',
      'Fictional clean compliance record',
    ],
  },
  {
    sellerKey: 'seller-second',
    title: 'Lithuanian EMI Licence',
    summary: 'Fictional EEA electronic-money institution opportunity with passporting potential.',
    description:
      'A fictional licence-led asset used to evaluate filters, detail views, Smart Match, and marketplace contact flows.',
    category: 'EMI',
    countryCode: 'LT',
    licenseType: 'EMI',
    regulator: 'Bank of Lithuania',
    businessStatus: 'LICENSE_ONLY',
    askingPriceEur: 780000,
    employeeCount: 3,
    highlights: ['EEA jurisdiction', 'Compact transition team', 'Fictional licence package'],
  },
  {
    sellerKey: 'seller-primary',
    title: 'Irish RegTech Platform',
    summary: 'Fictional profitable compliance software business serving financial institutions.',
    description:
      'A fictional operating software company that broadens the demo inventory and makes category and price filters meaningful.',
    category: 'FINTECH',
    countryCode: 'IE',
    licenseType: null,
    regulator: null,
    businessStatus: 'PROFITABLE',
    askingPriceEur: 3200000,
    employeeCount: 34,
    highlights: ['Recurring SaaS revenue', '34-person team', 'Fictional enterprise customers'],
  },
  {
    sellerKey: 'seller-second',
    title: 'Malta Crypto Service Provider',
    summary: 'Fictional pre-revenue virtual-financial-asset licence opportunity.',
    description:
      'A fictional listing used to demonstrate status/category filtering and lower-confidence matching.',
    category: 'CRYPTO',
    countryCode: 'MT',
    licenseType: 'VFA',
    regulator: 'MFSA',
    businessStatus: 'PRE_REVENUE',
    askingPriceEur: 450000,
    employeeCount: 1,
    highlights: ['Malta jurisdiction', 'Pre-revenue setup', 'Fictional regulatory package'],
  },
] as const;
